name = "twitter-proxy"
main = "src/index.js"
compatibility_date = "2023-06-26"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

# Twitter API 키는 Cloudflare Dashboard에서 환경변수로 설정
# TWITTER_CONSUMER_KEY = "your_consumer_key"
# TWITTER_CONSUMER_SECRET = "your_consumer_secret" 
# TWITTER_ACCESS_TOKEN = "your_access_token"
# TWITTER_ACCESS_TOKEN_SECRET = "your_access_token_secret"
# TWITTER_BEARER_TOKEN = "your_bearer_token"